apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: jiucom
  labels:
    app: jiucom
    component: grafana
spec:
  type: ClusterIP
  selector:
    app: jiucom
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
      name: http
