apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: jiucom
  labels:
    app: jiucom
    component: prometheus
spec:
  type: ClusterIP
  selector:
    app: jiucom
    component: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      name: http
