apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: jiucom
  labels:
    app: jiucom
    component: redis-exporter
spec:
  type: ClusterIP
  selector:
    app: jiucom
    component: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics
