apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: jiucom
  labels:
    app: jiucom
    component: zipkin
spec:
  type: ClusterIP
  selector:
    app: jiucom
    component: zipkin
  ports:
    - port: 9411
      targetPort: 9411
      name: http
