apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: jiucom
  labels:
    app: jiucom
    component: redis
spec:
  clusterIP: None
  selector:
    app: jiucom
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
