apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: jiucom
  labels:
    app: jiucom
    component: nginx
spec:
  type: LoadBalancer
  selector:
    app: jiucom
    component: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
