apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: jiucom
  labels:
    app: jiucom
    component: mysql
spec:
  clusterIP: None
  selector:
    app: jiucom
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
