apiVersion: v1
kind: Service
metadata:
  name: jiucom-api
  namespace: jiucom
  labels:
    app: jiucom
    component: api
spec:
  type: ClusterIP
  selector:
    app: jiucom
    component: api
  ports:
    - port: 8080
      targetPort: 8080
      name: http
